[package]
name = "pass_crack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
md-5 = "0.10.1"
hex = "0.4.3"
clap = { version = "3.2.14", features = ["derive"] }
